build/ubuntu-22.04: rerog repos & build guest (#474)
Signed-off-by: Xing, Haokun <haokun.xin@intel.com>

diff --git a/build/ubuntu-22.04/pkg-builder b/build/ubuntu-22.04/pkg-builder
--- a/build/ubuntu-22.04/pkg-builder
+++ b/build/ubuntu-22.04/pkg-builder
@@ -4,6 +4,35 @@ THIS_DIR=$(readlink -f "$(dirname "$0")")
 BUILD_DIR="${THIS_DIR}/.."
 BUILDER=pkg-builder-ubuntu-22.04
 
+INTERACTIVE=false
+COMMAND=""
+
+usage() {
+    cat << EOM
+Usage: $(basename "$0") [OPTION]...
+  -i                        Open interactive pseudo-terminal of the container
+  -c                        Command to run in the container
+  -h                        Show this help
+EOM
+}
+
+process_args() {
+    while getopts ":c:ih" option; do
+        case "$option" in
+            c) COMMAND=$OPTARG;;
+            i) INTERACTIVE=true;;
+            h) usage
+               exit 0
+               ;;
+            *)
+               echo "Invalid option '-$OPTARG'"
+               usage
+               exit 1
+               ;;
+        esac
+    done
+}
+
 check_docker_cmd() {
     if ! command -v docker &> /dev/null; then
         echo "Please install docker first."
@@ -25,27 +54,31 @@ build_docker_image() {
 
 # shellcheck disable=SC2086
 run_in_docker() {
+    MOUNT_POINT="/root/build/"
     DOCKER_ARGS=" \
         -e http_proxy -e https_proxy -e no_proxy \
-        -v ${BUILD_DIR}:/root/build \
-        -w /root/build/ubuntu-22.04 \
+        -v ${BUILD_DIR}:${MOUNT_POINT} \
+        -w ${MOUNT_POINT}/ubuntu-22.04 \
 	--rm \
     "
 
-    if [ $1 == "--shell" ]; then
-      docker run ${DOCKER_ARGS} \
-        -it \
-        "${BUILDER}" bash
+    if [[ $INTERACTIVE == "true" ]]; then
+        docker run ${DOCKER_ARGS} \
+            -it \
+            "${BUILDER}" bash
     else
-      docker run ${DOCKER_ARGS} \
-        -i --entrypoint "/root/build/ubuntu-22.04/$1" \
-        "${BUILDER}" $2
-    fi
+        docker run ${DOCKER_ARGS} \
+            -i \
+            "${BUILDER}" $@
+    fi  
+    
 }
+
+process_args "$@"
 
 check_docker_cmd
 check_user_in_docker
 build_docker_image
 
 # Run ansible-playbook within docker
-run_in_docker "$@"
+run_in_docker $COMMAND
